name: Run UI Tests in Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ui-tests:
    name: Run Playwright + Reqnroll Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t uiplayground .

      - name: Run UI tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            uiplayground

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
